{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: {{ .Values.externalSecrets.postgresSecretKey }}
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.externalSecrets.postgresSecretKey }}
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.postgresSecretKey }}
        property: POSTGRES_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.postgresSecretKey }}
        property: DATABASE_URL
{{- end }}
