---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install base packages
  ansible.builtin.apt:
    name:
      - curl
      - git
      - unzip
      - docker.io
    state: present
