apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: inventory-dev
type: Opaque
stringData:
  POSTGRES_DB: inventory
  POSTGRES_USER: inventory
  POSTGRES_PASSWORD: inventory
  DATABASE_URL: postgresql+psycopg2://inventory:inventory@postgres:5432/inventory
